
export const serviceRequests = [
  "Water: General Parameters",
  "Water Complete Analysis as per 10500: 2012",
  "Water - Construction Parameters",
  "Water - Microbiological Analysis",
  "Water –Complete Microbiological Analysis",
  "Food Microbiological Parameters",
  "Food Chemical Parameters",
  "Sludge Analysis Parameters",
  "Soil Testing Parameters",
  "Oil - Diesel Testing Parameters",
  "Oil - Nutrition Value + FSSAI Parameters",
  "Coal Analysis Parameters",
  "Effluent Water Analysis Parameters",
  "Sewage Water Chemical Parameters",
  "Ambient Air Quality Monitoring Parameters",
  "DG Stack Emission Parameters",
  "Ambient Noise Monitoring Parameters",
  "DG Noise Monitoring Parameters",
  "Lux Monitoring Parameters",
  "Indoor Air Quality",
  "Compressor Air Monitoring Parameters",
  "Feldspar Analysis Parameter",
  "Quartz Sample Analysis Parameters",
  "Lime Stone Sample Analysis Parameters",
  "Plate - Microbiological Analysis",
  "Swab - Microbiological Analysis",
  "Sewage Water Microbiological Parameters",
  "Weather Monitoring Parameters",
  "Oxygen Purity Parameters" 
];

export const serviceTypes = [ 
  { name: "Water: General Parameters", code: "W" }, 
  { name: "Water Complete Analysis as per 10500: 2012", code: "W" }, 
  { name: "Water - Construction Parameters", code: "W" }, 
  { name: "Water - Microbiological Analysis", code: "W" }, 
  { name: "Water –Complete Microbiological Analysis", code: "W" }, 
  { name: "Food Microbiological Parameters", code: "FM" }, 
  { name: "Food Chemical Parameters", code: "FC" }, 
  { name: "Sludge Analysis Parameters", code: "SW" }, 
  { name: "Soil Testing Parameters", code: "S" }, 
  { name: "Oil - Diesel Testing Parameters", code: "MM" }, 
  { name: "Oil - Nutrition Value + FSSAI Parameters", code: "MM" }, 
  { name: "Coal Analysis Parameters", code: "MM" }, 
  { name: "Effluent Water Analysis Parameters", code: "WW" }, 
  { name: "Sewage Water Chemical Parameters", code: "WW" }, 
  { name: "Ambient Air Quality Monitoring Parameters", code: "AS" }, 
  { name: "DG Stack Emission Parameters", code: "AS" }, 
  { name: "Ambient Noise Monitoring Parameters", code: "AS" }, 
  { name: "DG Noise Monitoring Parameters", code: "AS" }, 
  { name: "Lux Monitoring Parameters", code: "AS" }, 
  { name: "Indoor Air Quality", code: "AS" }, 
  { name: "Compressor Air Monitoring Parameters", code: "AS" }, 
  { name: "Feldspar Analysis Parameter", code: "MM" }, 
  { name: "Quartz Sample Analysis Parameters", code: "MM" }, 
  { name: "Lime Stone Sample Analysis Parameters", code: "MM" }, 
  { name: "Plate - Microbiological Analysis", code: "EM" }, 
  { name: "Swab - Microbiological Analysis", code: "EM" }, 
  { name: "Sewage Water Microbiological Parameters", code: "EM" }, 
  { name: "Weather Monitoring Parameters", code: "EM" }, 
  { name: "Oxygen Purity Parameters", code: "EM" } ];


export const staffOptions = {
  option1 : [
    "Elumalai",
    "Hemavathy",
    "Nalina",
    "Sindhuja",
    "Jeyarani",
    "Nagalakshmi",
  ],
  option2 : [
    "Vinaya",
    "Vinitha"
  ],
  option3 : [
    "Manimaran",
    "Iliyas"
  ],
}

export const parameterOptions = {
  firstOptions : [
    "Appearance",
    "Colour (Hazen Unit)",
    "Odour",
    "Turbidity (NTU)",
    "EC at 25°C (Micromhos/cm)",
    "pH at 25°C",
    "Total Suspended Solids",
    "Total Dissolved Solids",
    "Phenolphthalein Alkalinity as CaCO₃",
    "Total Alkalinity as CaCO₃",
    "Total Hardness as CaCO₃",
    "Calcium Hardness as CaCO₃",
    "Calcium as Ca",
    "Magnesium Hardness as CaCO₃",
    "Magnesium as Mg",
    "Chlorides as Cl",
    "Sulphates as SO₄",
    "Iron (Total) as Fe",
    "Silica (Reactive) as SiO2",
    "Carbonate Hardness",
    "Non-Carbonate Hardness",
    "Free Residual Chlorine"
  ],
  secondOptions : [
    "pH value @ 25oC",
    "Color ( Hazen Unit )",
    "Odor",
    "Taste",
    "Turbidity (NTU)",
    "Total Hardness as CaCO3 (mg/l)",
    "Total Iron as Fe(mg/l)",
    "Chlorides as Cl(mg/l)",
    "Free residual chlorine (mg/l)",
    "Total Dissolved Solids (mg/l)",
    "Calcium as Ca (mg/l)",
    "Magnesium as Mg (mg/l)",
    "Copper as Cu (mg/l)",
    "Manganese as Mn(mg/l)",
    "Sulphates as SO4(mg/l)",
    "Nitrate as No3 (mg/l)",
    "Fluoride as F (mg/l)",
    "Phenolic compounds (as C6H5OH) (mg/l)",
    "Mercury as Hg (mg/l)",
    "Cadmium as Cd (mg/l)",
    "Selenium as Se (mg/l)",
    "Arsenic as As (mg/l)",
    "Cyanide as CN( mg/l)",
    "Sulphide as H2S (mg/l)",
    "Lead as Pb (mg/l)",
    "Zinc as Zn (mg/l)",
    "Anionic detergents (as MBAS)(mg/l)",
    "Chromium as Cr6+( mg/l)",
    "Polynuclear aromatic hydrocarbons (asPAH) (mg/l)",
    "PolyChlorinated Biphenyls (mg/l)",
    "Total Alkalinity as CaCO3(mg/l)",
    "Aluminium as Al(mg/l)",
    "Boron as B (mg/l)",
    "Mineral oil (mg/l)",
    "Barium as Ba (mg / l)",
    "Ammonia as NH3(mg/l)",
    "Silver as Ag(mg/l)",
    "Molybdenum (mg/l)",
    "Nickel as Ni (mg/l)",
    "Chloramines as NH2Cl (mg/l)",
    "Trihalomethane as CHX3 (mg/l)",
    "Pesticides (µg/l)",
    "Alachlor (µg/l)",
    "Atrazine (µg/l)",
    "Aldrin/Dieldrin (µg/l)",
    "Alpha HCH (µg/l)",
    "Beta HCH (µg/l)",
    "Butachlor (µg/l)",
    "Chlorpyriphos (µg/l)",
    "Delta HCH (µg/l)",
    "2,4-Dichlorophenoxyacetic acid (µg/l)",
    "DDT(o,p and p, p-Isomers of DDT,DDE& DDD) (µg/l)",
    "Endosulfan (Alpha, Beta, and sulphate)",
    "Ethion (µg/l)",
    "Gamma-HCH(Lindane) (µg/l)",
    "Isoprotuoron (µg/l)",
    "Malathion (µg/l)",
    "Methyl Parathion(µg/l)",
    "Monocrotophos (µg/l)",
    "Phorate analogues (µg/l)",
    "Alpha Emitter(Bq/L)",
    "Beta Emitter(Bq/L)",
  ],
  thirdOptions : [
    "Organic Solids (mg/ l)",
    "Inorganic Solids (mg/ l)",
    "Sulfate as So3 (mg/ l)",
    "Chloride as Cl (mg/ l)",
    "Total Suspended Solids (mg/ l)",
    "pH value @ 25oC",
    "To neutralize 100 ml of water using Phenolphthalein indicator (ml)with 0.02N NaoH",
    "To neutralize 100 ml of water Using Methyl Orange indicator(ml)with 0.02 N H2SO4",
  ],
  fourthOptions : [
    "Total Coliforms",
    "E-Coli",
  ],
  fifthOptions : [
    "Total microbial count (cfu/ml) a. at 20 -22 C in 72 hours b. At 37 C in 24 hours.",
    "Total yeast and mould count",
    "E.coli",
    "Enterobacteriaceae (Coliforms)",
    "Faecal streptococci",
    "S. aureus",
    "Sulphite reducing anaerobes",
    "Salmonella",
    "Shigella",
    "V. cholera",
    "V. parahaemolyticus",
    "Ps. aeruginosa"
  ],
  sixthOptions : [
    "Total Bacterial Count",
    "Yeast & Mould",
    "Total Coliform ",
    "E. coli",
    "Staphylococcus aureus",
    "Salmonella Sp",
  ],
  seventhOptions : [
    "Moisture",
    "Total Ash",
    "Protein",
    "Carbohydrate",
    "Fat",
    "Acid Insoluble Ash",
    "Energy",
    "Crude Fiber"
  ],
  eighthOptions : [
    "Moisture",
    "Aluminium",
    "Arsenic",
    "Calcium",
    "Chromium",
    "Copper",
    "Iron",
    "Lead",
    "Loss on Ignition",
    "Magnesium",
    "Manganese",
    "Nickel",
    "Oil & Grease",
    "Phosphate",
    "Potassium",
    "Silica",
    "Sodium",
    "Sulphate",
    "Zinc"
  ],
  ninethOptions : [
    "pH",
    "EC",
    "Moisture",
    "Density",
    "Color",
    "Consistency",
    "Structure",
    "Texture",
    "Loss On Ignition",
    "Lime status ",
    "Alkalinity",
    "Sodium Absorption Ratio",
    "Cation Exchange Ratio",
    "Oil & Grease",
    "Chlorides",
    "Sulphates",
    "Nitrates",
    "Total Nitrogen",
    "Total Phosphorous",
    "Calcium",
    "Magnesium",
    "Sodium",
    "Potassium",
    "Iron",
    "Organic Matter",
    "Water Holding Capacity",
    "Copper",
    "Nickel",
    "Chromium",
    "Lead",
    "Zinc",
  ],
  tenthOptions : [
    "Density",
    "Viscosity@40oC",
    "Total Acid Number",
    "Water Content",
    "Pour Point",
    "Flash Point",
    "Fire Point",
    "Ash Content",
    "GCV",
    "Sulphur Content"
  ],
  eleventhOptions : [
    "Moisture",
    "Total Ash",
    "Protein",
    "Carbohydrate",
    "Total Fat",
    "Fibre",
    "Energy",
    "Refractive Index at 40 deg.C",
    "Saponification Value",
    "Iodine Value (Wij’smethod)",
    "Polenske Value",
    "Acid Value",
    "Unsaponifiable Matter",
    "Test for Mineral Oil",
    "Test For Argemone Oil",
    "Test for Castor Oil",
    "Test For Rancidity"
  ],
  twelfthOptions : [
    "Moisture",
    "Volatile Matter (VM)",
    "Ash",
    "Fixed Carbon",
    "Carbon",
    "Hydrogen",
    "Nitrogen",
    "Sulphur",
    "Oxygen"
  ],
  thirteenthOptions : [
    "pH at 25OC",
    "Total Suspended Solids (TSS)",
    "Total Dissolved Solids (TDS)",
    "BOD 3 Days at 27° C",
    "COD",
    "Chlorides as Cl",
    "Sulphates as SO4",
    "Oil & Grease"
  ],
  fourteenthOptions : [
    "pH",
    "Total Suspended Solids (TSS)",
    "Total Dissolved Solids (TDS)",
    "Chemical Oxygen Demand",
    "Bio chemical Oxygen Demand",
    "Total Nitrogen",
    "Total Phosphorus",
    "Oil & Grease"
  ],
  fifteenthOptions : [
    "Sulphur Dioxide (SO2)",
    "Nitrogen Dioxide (NOx)",
    "Particulate Matter (size less than 10µm)",
    "Particulate Matter (size less than 2.5µm))",
    "Ozone (O3)",
    "Lead (Pb)",
    "Carbon Monoxide (CO)",
    "Ammonia (NH3)",
    "Benzene (C6H6)",
    "Benzo Pyrene ",
    "Arsenic (As)",
    "Nickel (Ni)"
  ],
  sixteenthOptions : [
    "Flue Gas Temperature",
    "Flue Gas Pressure",
    "Flue Gas Velocity",
    "Volume of Gas Discharged",
    "Particulate Matter (PM)",
    "Sulphur- di- oxide (SO2)",
    "Nitrogen oxides (NOx)",
    "Carbon – di - oxide (CO2)",
    "Carbon Monoxide (CO)",
    "Oxygen (O2)"
  ],
  seventeenthOptions : [
    "Noise"
  ],
  eighteenthOptions : [
    "Before Acoustic",
    "After Acoustic",
    "Total Insertion Loss",
  ],
  nineteenthOptions : [
    "Illumination"
  ],
  twenteenthOptions : [
    "Air movements (At Workstation within occupied Zone)",
    "Carbon dioxide in (ppm )",
    "Carbon monoxide (ppm)",
    "Oxides of nitrogen concentration -µg/m3",
    "Oxygen in %",
    "Relative Humidity in %",
    "Respirable suspended particulate matter (RSPM) concentration (µg/m3)",
    "Temperature in ˚C",
    "Sulphur- di- oxide (SO2)",
    "Oil Mist"
  ],
  twentyFirstOptions : [
    "Oxygen Concentration by Volume (dry Air)",
    "Carbon Monoxide as CO",
    "Carbon Di-Oxide as CO2",
    "Water Vapour as H2O",
    "Oil Components",
    "Odor",
    "Dust Concentration (Wet/dry)"
  ],
  twentySecondOptions : [
    "Silica as SiO2",
    "Alumina as Al2O3",
    "Iron as Fe2O3",
    "Potassium as K2O",
    "Sodium as Na2O",
    "LOI",
    "Calcium as CaO",
    "Magnesium as MgO"
  ],
  twentyThirdOptions : [
    "Sillica as SIO2",
    "Alumina as Al2O3",
    "Iron as Fe2O3",
    "Calcium as CaO",
    "Magnesium as MgO",
    "Loss On Ignition",
    "Potassium as K2O",
    "Sodium as Na2O",
    "EC"
  ],
  twentyFourthOptions : [
    "Magnesium as MgCO3",
    "Calcium as CaCO3",
    "Alumina as Al2O3",
    "Iron as Fe2O3",
    "Sodium as Na2O",
    "Potassium as K2O",
    "Silica as SiO2",
    "LOI"
  ],
  twentyFifthOptions : [
    "Bacterial count - 37°C for 48 hrs",
    "Fungal Count -25°C for 5 Days"
  ],
  twentySixthOptions : [
    "Bacterial count - 37°C for 48 hrs",
    "Fungal Count -25°C for 5 Days",
    "Total Coliform",
    "E. coli",
    "Staphylococcus aureus"
  ],
  twentySeventhOptions : [
    "Total Platel count (cfu/ml)",
    "Total Coliform",
    "E.coli",
    "Fecal Coliforms",
    "Faecal streptococci"
  ],
  twentyEighthOptions : [
    "Micro Metrology",
    "Wind direction",
    "Wind Velocity",
    "Temperature",
    "Relative Humidity"
  ],
  twentyNinethOptions : [
    "Oxygen Purity ( O2)"
  ]
}